### ISSUE TITLE
Replace language icons with pseudo-elements

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#1368]
## User story

Fred desperately wants to see fewer DOM nodes. It's his, like, thing. Every day, he opens up SuttaCentral and runs Lighthouse, just hoping that the DOM count drops. Alas, on staging it is still too high: **3,528** nodes. He feels sad.

Thanks to sleuthing by our devs, we know that the icons are a major factor. We have removed extra unused iron-icons already: what more can be done?

## Feature description

The language iso code icons are many and create a lot of DOM. But they are also very simple and can be created with a few lines of CSS. Doing so not only reduces DOM, it removes a dependency and is much easier to maintain. As languages have been added to `sc-language-icons` they have sometimes been ill-made, with unnecessary cruft. It's all a bit wasteful, as the paths in the svgs are really just the letter shapes of Skolar anyway.

I have made a proof-of-concept for using pseudo-elements instead of svg icons. It's on sujato-work branch.

https://github.com/suttacentral/suttacentral/commit/bbc422da1bcb55d3edd6ecbcee1593e12d967573

This is so far in the language selector of the toolbar menu only, not the sidebar (see below). No extra JS is needed, in fact we can remove some existing JS and simply use the already-present classes and IDs. 

Using a CSS-only approach, we can create a pseudo-element on `.language-menu-paper-item` for the styling. A condensed style can be used for the three-letter codes; again, no extra classes need be created. I gave the boxes notched corners *just because I could*. I find the old icons a little hard to read, so I got rid of the "speech-bubble" notch, which allowed a little more vertical space.

Then we use CSS `attr` to choose the ID:

     .language-menu-paper-item::before {
        content: attr(id);

DOM count for me locally after doing this: **2,863**. Getting there!

## To-do

- There is a bug on the selected language, the icon appears in the wrong place and color, then corrects itself after an event. https://github.com/suttacentral/suttacentral/issues/1373
- The same approach should be applied to the sidebar language icons (see comment). This is not critical, the feature can go live as-is and we can do the sidebar later.

## Acceptance criteria (the list of things that need to be done for the ticket to be considered finished):

- Fix bug on "selected language".
- Test on devices.

#### Pre milestone planning check:
- [ ] Small enough to completed in a milestone.
- [ ] Dependencies marked
- [ ] No external dependencies block the PBI from being completed.
- [ ] Details are understood by dev team to decide if the PBI can be completed.

#### Done check:
- [ ] Produced code for presumed functionalities
- [ ] Project builds without errors
- [ ] Peer Code Review performed/pull request approved x2
- [ ] Project deployed on the stage environment identical to production platform
- [ ] Feature is tested against acceptance criteria
- [ ] Feature ok-ed by Product Owner (moving to Closed on the Board)
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented (readme, etc...)

**Comment by sujato** [comment]
With this commit:

https://github.com/suttacentral/suttacentral/commit/22eb2e8bdb21a68801353731325c8b9264ae25f7

I made a first pass at using pseudo-icons in sidebar. It works in some cases, but I don't understand the logic so much is broken. Anyway, it shows it can be done, and the DOM count is now down to 2,544.
