### ISSUE TITLE
Add table of content to texts.

### ISSUE THREAD

**Issue by ihongda** [suttacentral/suttacentral#1556]
## To-do

- [ ] Icon and ToC are **only** on texts that actually have a ToC, i.e. only on texts with an `<h2>`.
     - See https://staging.suttacentral.net/mn3/en/sujato. It seems inconsistent, eg here there is no ToC: https://staging.suttacentral.net/mn5/en/sujato
- [x] Icon label is "contents" not "toc".
- [x] Add a heading to the contents `<h2>Table of Contents</h2` (See info top sheet for implementation)

***

Currently segmented text on SC have a Table of Contents (ToC). For example:

https://suttacentral.net/dn16/en/sujato

However the updated site does not have ToC:

https://staging.suttacentral.net/dn16/en/sujato

And legacy texts do not have ToC in either new or old versions:

https://suttacentral.net/dn16/en/anandajoti

All texts with subheadings should generate a ToC. This means all texts that have an `<h2>` tag.

## Implementation

Rather than the old approach of putting the ToC on the page, add it instead to a "top sheet" accessed via the `context_toolbar`. 

The top sheet and associated icon is only added for texts that do, in fact, have a ToC.

The top sheet will essentially be identical with the current "info" and "parallels" sheets, just add the ToC to a new sheet.

Use the Material icons `toc` icon, with text `contents`. 

https://material.io/resources/icons/?search=content&icon=toc&style=baseline

When you click the icon, the top sheet appears with the ToC. That's about it.

Don't worry about styling, just get the content in the sheet, I'll style it.

**Comment by sujato** [comment]
I have fixed all these except the display on pages that have no ToC.
