### ISSUE TITLE
Sujato SC 5.0 remaining to-do

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#2014]
- [x] Introduce Carmi and get her working with translators
- [x] Update text corrections
- [x] Publish bilara texts
- [x] Tracy's segment update https://discourse.suttacentral.net/t/sc-data-structure/17685/21
- [x] make PR summary of changes on upgrade

**Comment by sujato** [comment]
Blurbs for AN5.17-20:

    “an5.17”: “By practicing but not teaching, one practices for one’s own good.”,
    “an5.18”: “By teaching but not practicing, one practices for the good of both.”,
    “an5.19”: “By neither teaching nor practicing, one doesn’t practice for anyone’ good.”,
    “an5.20”: “By both teaching and practicing, one practice for everyone’s good.”,

AN5.18 should be “for the good of others”.

Blurb for AN5.33:

    Uggaha invites the Buddha for a meal, and asks him to advise his daughters, who about about to be married.

Should be “who are about to be married”.

**Comment by sujato** [comment]
Blurb for AN5.38:

    When someone is a donor, the reap the benefits of association with the Saṅgha.

Probably: they reap …

**Comment by sujato** [comment]
The nun Vajirā’s name is lacking in her blurb:

    “sn-blurbs:sn5.10”: “Māra asks the nun about who has created this being. Recognizing him, she points out that the word “being” is nothing more than a convention used to designate the aggregates, just as the word “cart” is used when the parts are assembled”,

**Comment by sujato** [comment]
SN 10 blurb:

    The “Linked Discourses with Spirits” contains 12 discourses with verses telling the encounters between the Buddha—or in one case the monk Anuruddha—and various spirits (yahhka). …

Typo: should be yakkha instead of yahhka.

**Comment by sujato** [comment]
n the blurb to SN 35 it says when talking on the sixth sense field:

    The outer aspect is dhammā, a term so ambiguous its translation is always difficult. Here it refers to anything that may be known directly by the mind, distinct from the six senses.

Shouldn’t it be the five senses instead of six?

**Comment by sujato** [comment]
sn-sagathavaggasamyutta blurb:

    Most of the suttas here have parallels in the Chinese Saṁyukāgama translations

Is it “Saṁyukāgama” or “Saṁyuktāgama”?
