### ISSUE TITLE
Show more meta data in search results list to give more context

### ISSUE THREAD

**Issue by thesunshade** [suttacentral/suttacentral#2718]
#### User story
Someone does a search for "forgiveness". They are interested in forgiveness as a doctrinal concept, not really its formal role in monastic procedures. Many of the results will be in the Vinaya. However there is nothing to indicate this.

Usually the suttaplex cards are being viewed within a context where the user knows how they got to this place. But the search results are removed from this context. And within each "basket" the user would also likely be aware of the language of the root text because they decided to go down that part of the tree. But in the search results, this is not apparent. 

![image](https://github.com/suttacentral/suttacentral/assets/82448383/cb776c4e-9bb8-4ddd-b38e-f00e525652ef)

An experienced user might know (or think they know) that Ven. Brahmali has only done translations of the Vinaya. And they might know that citations to "Bu", "Bi" and "Kd" are all to the Vinaya. But an ordinary user would not.

Further down the page we see a citation with a "T"
![image](https://github.com/suttacentral/suttacentral/assets/82448383/25cdfac3-9c70-449d-a6d3-53d6bc623228)

Someone experienced with Pali might know this isn't a Pali root text, but they would have no idea exactly what the root language of the text was

#### Feature description

Add some kind of meta data to indicate at least what "basket" the text was in. Also some indication of language would be beneficial. 

Perhaps this could be done through adding css classes and then doing a `.vinaya::before{content:"Vinaya"}` thing

#### Pre milestone planning check:
- [ ] Small enough to completed in a milestone.
- [ ] Dependencies marked
- [ ] No external dependencies block the PBI from being completed.
- [ ] Details are understood by dev team to decide if the PBI can be completed.

#### Done check:
- [ ] Produced code for presumed functionalities
- [ ] Project builds without errors
- [ ] Peer Code Review performed/pull request approved x2
- [ ] Project deployed on the stage environment identical to production platform
- [ ] Feature is tested against acceptance criteria
- [ ] Feature ok-ed by Product Owner (moving to Closed on the Board)
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented (readme, etc...)

**Comment by sujato** [comment]
Good idea, we can add the collection, something like "Vinaya Khandhaka 12" or whatever, and maybe the root language also.

**Comment by ihongda** [comment]
![screenshot_2023-12-15_12-12-49](https://github.com/suttacentral/suttacentral/assets/4037966/6a4d66bc-1d9e-4291-a3d8-4294363bd7d7)

I made a prototype that provides more meta information.
