### ISSUE TITLE
Add missing segments to the internationalization file

### ISSUE THREAD

**Issue by thesunshade** [suttacentral/suttacentral#2729]
- [x] "More awesome SuttaCentral things" on homepage
- [x] [Previous and next at the bottom of suttas](https://github.com/suttacentral/suttacentral/issues/2729#issuecomment-1913055928)
- [x] [Help text on click to lookup dictionary
](https://github.com/suttacentral/suttacentral/issues/2729#issuecomment-1656542122)
- [x] [buddhism.net in footer](https://github.com/suttacentral/suttacentral/issues/2729#issuecomment-1913047962)
- [ ] [License abbreviation?](https://github.com/suttacentral/suttacentral/issues/2729#issuecomment-1913057804)
- [ ] ~~[License description?](https://github.com/suttacentral/suttacentral/issues/2729#issuecomment-1913057804)~~
- [x] Buddhism.net blurb on homepage (replacing Bilara info [here](https://github.com/suttacentral/bilara-data/blob/4a99f417e7c14424e48634dd44b08c9068515622/root/en/site/home_root-en-site.json#L31C3-L33C13])
- [x] The whole editions page needs to be localized https://suttacentral.net/editions (maybe you are waiting until there are editions in other languages?)
- [x] The [Pali Canon Overview](https://suttacentral.net/pali-tipitaka?lang=en) Page. See [notes below](https://github.com/suttacentral/suttacentral/issues/2729#issuecomment-1937856342).

**Comment by thesunshade** [comment]
Found another. Should include "Help" and "Close"

![image](https://github.com/suttacentral/suttacentral/assets/82448383/6370b18b-35b1-4bff-a59e-a80af496d864)

I also wonder if 
```
"donate:feeDisclaimer": "The Stripe handling fee deducted from a donation is 1.75% + 30¢ for Australian cards, and 2.9% + 30¢ for International cards, plus a 1.8% currency conversion fee when applicable.",
```
Should this be done in such a way so that it doesn't need to be updated in all the language files when the fees go up? Maybe not worth the trouble.

**Comment by thesunshade** [comment]
![image](https://github.com/suttacentral/suttacentral/assets/82448383/3b38a604-7727-4dca-af1e-41c8cb04e205)

It looks like this needs to be internationalized.

**Comment by thesunshade** [comment]
@ihongda There is also the text of the new buddhism.net blurb on the homepage

https://github.com/suttacentral/bilara-data/blob/4a99f417e7c14424e48634dd44b08c9068515622/root/en/site/home_root-en-site.json#L31C3-L33C13

![image](https://github.com/suttacentral/suttacentral/assets/82448383/97677ae1-7017-4cad-a0a7-275de48718b6)

While you are at it, could we shorten the subheading so that it doesn't overflow. It's much longer than the others in that area. 

How about `Easy access to the teachings`

![image](https://github.com/suttacentral/suttacentral/assets/82448383/6a616a2e-6a1d-4dd6-a213-839eaf79888f)

And can we remove the `1) 2) 3)` they are mega ugly and unnecessary.

**Comment by thesunshade** [comment]
![image](https://github.com/suttacentral/suttacentral/assets/82448383/f2887fea-d7c8-4c43-9522-5714865810a6)

The text of previous and next at the bottom of texts

**Comment by thesunshade** [comment]
There might be something missing under license? License abbreviation?

![image](https://github.com/suttacentral/suttacentral/assets/82448383/3bccada7-8518-43bc-8cad-47136cb2d680)
https://suttacentral.net/pli-tv-bu-vb-pj3/pli/ms?lang=en&layout=plain&reference=none&notes=none&highlight=false&script=latin

I have no idea if this is a localization issue or not.

Also the license description is not internationalized. Despite the text in the paragraph above it beign i18n, this is not because it is part of the publication data. If you look above at the other publication data, you can see that although the headings are i18l, the actual metadata is not. That's why the text below is still in English.

![image](https://github.com/suttacentral/suttacentral/assets/82448383/b2857571-ae87-4f97-9a51-568ce009bc06)


I find both the abbreviation and description here:
![image](https://github.com/suttacentral/suttacentral/assets/82448383/3d4eb077-0bcc-4972-be5b-7e6f7453ea61)
 
It also exists multiple times in this file:
![image](https://github.com/suttacentral/suttacentral/assets/82448383/4c52750c-744f-48e1-8aef-1a0c8841c6b8)

**Comment by sabbamitta** [comment]
> And can we remove the 1) 2) 3) they are mega ugly and unnecessary.

Can you please explain what you mean by this?

I've been looking into all these, and it's good to collect them all in one place. Thank you!

**Comment by thesunshade** [comment]
> Can you please explain what you mean by this?

The sentence reads perfectly fine without them. And they draw way too much attention to the eye for something that isn't needed. It's subjective, of course.

I'm really not keen on the whole paragraph. It's use of "we" matches the D&D description, but it's a completely separate group. It's also a bit verbose imo. "we hope to help", "we focus on", "we aim to offer"

It looks like the text was just grabbed from their site:

>At Buddhism.net, we hope to help you 1) learn Buddhism, 2) develop a practice, and 3) discover teachers and communities. Buddhism.net is cross-sectarian. We focus on early Buddhism, the common root of all modern forms of Buddhism. We aim to offer you a solid foundation in early Buddhism, which will be immensely helpful to you regardless of which form of Buddhism you adopt.

This is my suggestion for text that fits better in the context of the SuttaCentral home page: 

> Buddhism.net helps you learn Buddhism, develop a practice, and discover teachers and communities. Cross-sectarian, it focuses on early Buddhism, the common root of all schools of Buddhism. Build a solid foundation in early Buddhism, helpful no matter what form of Buddhism you follow.

**Comment by sabbamitta** [comment]
Ahhhh … I see now that you refer to the text on the card. I hadn't initially seen that card (it's only on staging, and even there only showed up after a hard refresh, and I hadn't been aware of any plans to replace the reference to Bilara on the Home page …), so it wasn't clear to me what you are talking about.

Why is Bilara going to be removed from there?

**Comment by thesunshade** [comment]
The [Pali Canon Overview](https://suttacentral.net/pali-tipitaka?lang=en) page is a static page. Individual segments on the page have (maybe?) been completely translated however those translations are spread across multiple localization files (i.e. the name files)

Normally static pages draw from a single `.json` file to get the segments.

If this page is going to be internationalized, then either 

* the code for internationalizing pages needs to be re-written so multiple source files can be used or
* a new .json file needs to be created and translators will have to translate these terms a second time. 
* or some other solution I haven't thought of.

The other two options I see are 
* deleting the page as it may not be necessary
* deciding not to localize it

**Comment by sabbamitta** [comment]
>
    deleting the page as it may not be necessary
    deciding not to localize it

If these are the two options to consider, I'd vote for the first one.

**Comment by thesunshade** [comment]
> I'd vote for the first one.

Even considering all four options, I'd probably vote for deleting it. Especially since it only includes Pali and it just doesn't feel like an efficient way to present the data. For an "overview" it's really spread out on the page.

**Comment by sabbamitta** [comment]
I am not sure. Do you have other ideas how an overview should look like? 

I think there are quite a lot of people who have no idea of how the Pali canon is organized, and perhaps a way to show them the basic structure would make sense. But I am not sure *how* this can be best achieved.

**Comment by thesunshade** [comment]
> I think there are quite a lot of people who have no idea of how the Pali canon is organized, and perhaps a way to show them the basic structure would make sense. But I am not sure _how_ this can be best achieved.

Yes and yes. 

It comes back to the fact that the way the site is currently designed, to localize anything like this it will be duplicating the translators work. Perhaps some custom page could be designed that could pull from multiple localization sources including blurbs. I think an overview like this ought to contain the blurbs too.

However at some point we just end up reproducing the navigation of the site, no?

**Comment by sabbamitta** [comment]
> However at some point we just end up reproducing the navigation of the site, no?

Yes, I've also had this thought.
>It comes back to the fact that the way the site is currently designed, to localize anything like this it will be duplicating the translators work.

It duplicates the work for *one page*, not for everything. But I understand that you are having a hard time to motivate interface translators, even without such a duplication … :smile: 

For me it would just be clicking through a number of segments I have already translated previously. :shrug:

**Comment by thesunshade** [comment]
There is also the fact (?) that for many of these book names there will be no standardized name for them in the local language. That means that a competent, but perhaps not a specialist, translator will be coming up with completely new names for these books. 

> But I understand that you are having a hard time to motivate interface translators, even without such a duplication

That's not an absolute factor, but yes, it's true. Also, there is the fact (?) that for many of these book names there will be no standardized name for them in the local language. That means that a competent, but perhaps not a specialist, translator will be coming up with completely new names for these books. And that kind of work is the hardest of all for them to do. 

> For me it would just be clicking through a number of segments I have already translated previously.

Right. For people using Bilara I guess it's not an issue as long as the English segments are identical? Perhaps that's the right answer. If Bhante Sujato feels confident in the page, then Bilara is the existing and proper solution.

**Comment by sabbamitta** [comment]
> Also, there is the fact (?) that for many of these book names there will be no standardized name for them in the local language. That means that a competent, but perhaps not a specialist, translator will be coming up with completely new names for these books

But the same thing can happen in the "name" files as well. It can and will happen on any level of translation you may imagine.
>Right. For people using Bilara I guess it's not an issue as long as the English segments are identical? Perhaps that's the right answer. If Bhante Sujato feels confident in the page, then Bilara is the existing and proper solution.

That's actually what it was built for! :smile_cat: 

And even if the English translations differ---Bilara always looks for the Pali to make it's translation suggestions.

**Comment by thesunshade** [comment]
> And even if the English translations differ---Bilara always looks for the Pali to make it's translation suggestions.

Ah, of course.

My only other issue (and it is not unique to this page) is that if translations are duplicated, then if one is updated the other is not. But considering that there are currently hardly any translations of the names files, I guess it doesn't matter much in the scheme of things.

**Comment by thesunshade** [comment]
@sabbamitta, I may have completed the code change to i18l the previous/next buttons. Lets see!

As far as the license description mentioned in my comment [here](https://github.com/suttacentral/suttacentral/issues/2729#issuecomment-1913057804), I have updated that comment to explain that the description is based on the publication metadata, not generic text. So while the description of the CC0 is reused and therefore i18l, the publication metadata is not. This was confusing because of its distance from the other metadata on the page. 

I have no idea if there will ever be the ability to translate the metadata for individual publication projects, so I will for now remove it from the checklist at the top of this issue.

**Comment by thesunshade** [comment]
I'm going to close this for now since it sounds like Bhante may want to wait till there are non-English editions to localize the editions page. Otherwise things are all localized. 

Feel free to re-open if you find anything else.

**Comment by sabbamitta** [comment]
![IMG_20241230_114842_548](https://github.com/user-attachments/assets/2e65fb5b-1b2e-4827-8b3f-f4be31c6124b)

**Comment by sabbamitta** [comment]
On some reference numbers, the popup text is not translated. It is translated for SC segment numbers, but I think for everything else it is not.

This needs to be added to Bilara for i18n, please.
