### ISSUE TITLE
Search bugs to be tested

### ISSUE THREAD

**Issue by ghost** [suttacentral/suttacentral#883]
The search still needs some improvements, here are some quirks that I notice as I go. 

Tested on Feb 2022.

- [x]  search for uppadetva gives no results. **Make sure to match diacriticals.**
- [x]  search for uppadetv gives no results. **Match parts of a word, especially when there are no full matches**.
- [x] https://suttacentral.net/search?query=digham+va+assasanto yields a lot of entries for "vā". Nearly the top sutta entry is the Metta Sutta! Ironically though, searching for "Metta Sutta" gives a bunch of results for "sutta", but not the Metta Sutta. **Prioritize full phrase, and if selecting for individual words, filter out the small ones.**
- [x] jīvitasaṅkhāra give no results.
- [x]  Dhammacakkappavattana doesn't bring up the Dhammacakkappavattanasutta. Which leads us to:
- [x] Priority should be given to sutta titles and collection titles
- [x] Catusparisat gives nothing. Catuṣpariṣat also gives nothing. 
- [ ] Make sure truncated forms with * return dictionary results.

**Comment by sujato** [comment]
Testing these, there are some new bugs:

- [x] Pali upper case is normalized to lower case in results: search for ānanda, the result results show ānanda highlighted even when it should be Ānanda.


![Screenshot from 2023-03-13 16-55-45](https://user-images.githubusercontent.com/6112010/224619207-bf6319ca-6af5-4da6-ada0-c25c808f4db0.png)


- [x] results only partial, then have to press "load more".


![Screenshot from 2023-03-13 16-53-11](https://user-images.githubusercontent.com/6112010/224618956-7b83c1d2-f326-4edb-95ba-78171883bc16.png)



- [x] search for Pali, get no text results, only heading


![Screenshot from 2023-03-13 16-51-14](https://user-images.githubusercontent.com/6112010/224618646-8a8210a5-b064-44ba-a331-f0f0110428b2.png)

**checking initial issues again**

- [x] text jīvitasaṅkhāra (random Pali word): 
    - says there are two results — only gives one
    - does not show text
    - the number of results is incorrect, there are in fact three sutta with this word.

![Screenshot from 2023-03-13 16-59-58](https://user-images.githubusercontent.com/6112010/224619734-1b1e725c-e3fe-44fc-88f4-d9c5dd3234e8.png)



- [x] search Dhammacakkappavattana 
    - still does not give the Dhammacakkappavattanasutta
    - says there are 9 results, but only shows two.

- [x] Catusparisat and Catuṣpariṣat both return eight results. 
     - but there is no text
     - the results are duplicated: each entry is shown twice


![Screenshot from 2023-03-13 17-03-54](https://user-images.githubusercontent.com/6112010/224620342-2a6c1bd2-22d8-4569-89e7-3f19129fb86b.png)

- [ ] wildcard search with `*` does not seem to work at all.

**Comment by thesunshade** [comment]
- [x] Search is not returning titles in legacy texts.

For example, "bright protectors" should return https://suttacentral.net/iti42/en/ireland

**Comment by sujato** [comment]
Results are still far from optimal.

Search `Ānanda`, now all results have *Capitalized* Ānanda even when it makes no sense (GirimĀnanda). 

- [x] Don't change the capitalization of results. lowercase stays lowercase, uppercase stays uppercase.

In addition, when Ānanda is in the title, the sutta gets returned *four times*! See 

https://staging.suttacentral.net/search?query=%C4%80nanda

look for 22.37 Ānandasutta

- once as the suttaplex
- once as the title of the Pali text
- once as the title of the English translation
- once more as the title of the Pali text

It makes the search borderline unusable.

- [ ] return any given sutta *once* only. 
- [x] If the search term is in the title, return the suttaplex, NOT the regular search result item.

Other cases are worse: 51.27 gives the German translation too.

**Comment by thesunshade** [comment]
Man, I feel your pain. I will say, though, that no matter what you do a search for Ānanda is probably always going to be borderline useless. 

Thanks for everyone's hard work!

**Comment by sujato** [comment]
Ha ha, well at least we can try.

***

Alrite, let's do `cat`.

https://staging.suttacentral.net/search?query=cat

- 20606 results --- seems like a lot, but okay!

I did the search again, now we have 21571 results. Not sure how I feel about that!

The first result is 

- Arv 27 — Eighty Lesser Indi**cat**ions

This should not be the top result:

- *whole word matches* should come first
- this is not an EBT; EBTs should come first

Generally the results are poor, it is a long list of sutta titles, mostly nothing to do with cats, and no text results in the initial search.

Now let's try `dog`.

https://staging.suttacentral.net/search?query=dog 

Woof! Now we have much better results. There are few empty titles, only ones that are in fact about a dog, so it is completely different than `cat`. 

The next thing we should optimize is to reduce the number of duplicate suttas. Here are the results.

![Screenshot from 2023-04-27 18-49-45](https://user-images.githubusercontent.com/6112010/234810703-d9b69efa-b1b9-40fe-8a73-4a6beed5216c.png)

As you can see, we get dn8 twice, then dn24 twice, then dn25 twice. This creates a lot of unnecessary noise in the results. 

Instead, we should only return a sutta once. If multiple translations have the search term, give the bilara translation. If there is no bilara translation, give another one.

Here are the same results with duplicates removed:

![Screenshot from 2023-04-27 18-54-43](https://user-images.githubusercontent.com/6112010/234812150-dd98b662-0294-46ca-b223-fc648271d47a.png)

Much more useful!

**Comment by ihongda** [comment]
Due to the increase of the index for each segmented text, some repetitive and less useful items were brought to the search results, so I added an option: `Match partial`, only when this option is checked, the partial matching function will be enabled, which both reduces some useless search results and improves the search speed.

**Comment by sujato** [comment]
I'm still getting zero results for uppaddetv, even with match partial checked. uppādetv works though.

I wonder if it would be better to put the "match partial" checkbox on the results page rather than in the filter dropdown? It could go underneath the "Hint".

**Comment by thesunshade** [comment]
> I wonder if it would be better to put the "match partial" checkbox on the results page rather than in the filter dropdown? It could go underneath the "Hint".

I think the partial search should be pulled out from the drop down. It's a fairly standard tick box in a search interface.

**Comment by thesunshade** [comment]
- [x] Restricting search to English should not return translations into other languages

Right?

When I do a search for `in:dn cat` I'm getting mostly non-english results:

![2023-07-10 09_07_17-Search_ in_dn cat — Mozilla Firefox](https://github.com/suttacentral/suttacentral/assets/82448383/414a39cb-fe00-46dc-89e5-6c03262294d3)

And despite the filters, it is still saying "in all languages"

![image](https://github.com/suttacentral/suttacentral/assets/82448383/65419089-05fb-4b45-b626-bbcfb9087bbb)

I did a bunch of hard refreshes and the results didn't change.

The first Vietnamese result does contain a form of "cat"
![image](https://github.com/suttacentral/suttacentral/assets/82448383/90e78585-b0b5-497f-9bc8-511006b6667c)

**Comment by thesunshade** [comment]
- [x] `in:` should work for all ids

Currently dn, mn, sn, and an work, however others (iti, snp etc. don't seem to)

- [ ] Filters like `in:dn` should be applied no matter where they are in the search string

I'm assuming this is the correct behaviour but I don't know.

**Comment by thesunshade** [comment]
- [x] `in:vinaya respect NOT feet` should at least be returning https://suttacentral.net/pli-tv-bu-vb-pc24/en/brahmali. Currently it returns nothing.

**Comment by thesunshade** [comment]
- [x] clicking search button should re-run search if "match partial" has been toggled

Say you have "match partial" ticked and you search for something. Then you want to search again but without "match partial" ticked. The app doe not recognize this is a new search, so clicking the search button does nothing.

**Comment by thesunshade** [comment]
- [x] Putting search terms in quotes should not result in an interface load error
![image](https://github.com/suttacentral/suttacentral/assets/82448383/96bf5bea-95b7-4155-8ddf-44d8f9ced6a6)

I don't know if you will support putting quotes around search terms, but for sure it shouldn't give this error.

**Comment by thesunshade** [comment]
- [x] "We found no results in the languages in your search language settings." should not be returning results in the language of my search settings.

I have only English ticked in my language choices. Searched for `Anāthapiṇḍika NOT Jeta` and got this:
![image](https://github.com/suttacentral/suttacentral/assets/82448383/1704c6e8-bada-416f-a082-f3580d57d780)

However… it actually returns a good English result: 
![image](https://github.com/suttacentral/suttacentral/assets/82448383/d49300b8-c422-4474-940f-ce476ec1df3c)

**Comment by thesunshade** [comment]
- [x] Text excerpt in search result should always show search term

`in:an arrow` returns this:

![image](https://github.com/suttacentral/suttacentral/assets/82448383/c83f3c1a-5659-4af7-8f89-842d100822fb)

First result the word "arrow" is not visible there in excerpt. It's actually the very first word elided. 

![image](https://github.com/suttacentral/suttacentral/assets/82448383/3758d89d-27ab-468a-b4ce-68d9e20db3e7)

Found another one `in:mn ascetic OR mendicant OR sage`

![image](https://github.com/suttacentral/suttacentral/assets/82448383/3ceedce4-cd9f-4517-808b-d8626be558d2)

**Comment by thesunshade** [comment]
- [x] Dictionary results should not appear twice

`saṁseva`

Gives this at the top:

![image](https://github.com/suttacentral/suttacentral/assets/82448383/d5978ecb-cea4-4028-b89e-edd26cc2bc53)

and this at the bottom:

![image](https://github.com/suttacentral/suttacentral/assets/82448383/01d6f0e7-cf89-47d4-ac48-a1aeb31d6f02)

**Comment by ihongda** [comment]
Thanks @thesunshade 🙏🏼

**Comment by thesunshade** [comment]
- [x] Search results should not be returned when term is merely found in sub-chapter name

For example, `in:sn stream` returns the following:
![image](https://github.com/suttacentral/suttacentral/assets/82448383/0c60d83d-0c56-4462-b0d8-ba5f85c83776)

All of those only hit because they are in the sub-chapter "1. Stream-Entry ". Nothing in the sutta itself has the term.

**Comment by thesunshade** [comment]
- [x] If the search term matches a *Pali* title, then it should be treated as if it were a search term in the English title.
(Note: the behaviour below is on staging. It seems to be working on production, but this should be confirmed.)

If someone knows the Pali title of the sutta, they should have a way to be taken to an English translation directly, not round about through the Pali text.

For example, searching for `Dhammacakkappavattana` gives you this:

![image](https://github.com/suttacentral/suttacentral/assets/82448383/06c35c85-5d75-4738-8ae9-cec3d5b3e5a5)

To get to a translation you have to dance through the MS text or the SuttaPlex card. That should not be necessary.

-----
- [x] Diacritics should not affect search results

For example, searching for `Ananda` gives this:

![image](https://github.com/suttacentral/suttacentral/assets/82448383/0f4f835b-4835-4ac8-b607-12e68e5a0abc)

But searching for `Ānanda` gives this:

![image](https://github.com/suttacentral/suttacentral/assets/82448383/57a108e7-b861-431e-850d-4d48366024a3)

---
(not sure if this is strictly search related)

- [x] In dictionary results, highlighted terms should be in the correct case, not in the case of the entered search term.
<img src="https://github.com/suttacentral/suttacentral/assets/82448383/6f610249-1625-40e6-a5a9-06dfdc0520bb" width="300" >


---
- [x] Partial matches should apply to dictionary results as well

Is it searching for exact results on purpose? Because there will be lots of names where people may drop the "maha." And it just seems wrong that searching for "Moggallana" gets you no dictionary entry. The dictionary does keep track of alternate names, which would be cool to have the search take into account, but that may be too complicated.

For example the search for `moggallana` gives not dictionary result:

![image](https://github.com/suttacentral/suttacentral/assets/82448383/b91e8c99-22b0-4ebc-8a4d-804928e2d8ed)

But searching for `mahamoggallana` does:

![image](https://github.com/suttacentral/suttacentral/assets/82448383/94915c55-bcb7-4911-bac9-9a877ef0499f)

**Comment by thesunshade** [comment]
> I'm still getting zero results for uppaddetv, even with match partial checked. uppādetv works though.

That's because there is only one "d". You have two. Were you expecting it to match?

I'm going to close this thread for now. I have created separate issues for things still broken.
