### ISSUE TITLE
Add English Vibhanga to Pootle

### ISSUE THREAD

**Issue by Aminah-SC** [suttacentral/suttacentral#900]
Ajahm Brahmali has translated the Bhikkhu & Bhikkhuni Vibhanga into English and these need to be added to Pootle. A lot of the Bhikkhu Vibhanga is already done but the rest is still to be added. 

#### Tasks:

- [ ] add texts to Pootle
- [ ] test texts on site after uploading
- [ ] test links in texts
- [ ] teach Ajahn how to make changes in Pootle

**Comment by Aminah-SC** [comment]
Superseded by #1045.
